modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId="rotp_sw"
version="${file.jarVersion}"
displayName="RotP Soft And Wet"
authors="Top1545, StandoByte"
description='''
An addon for Ripples of the Past mod, adding a new Stand - Soft And Wet.
'''
[[dependencies.rotp_sw]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_sw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_sw]]
    modId="jojo"
    mandatory=true
    versionRange="[0.2.2,0.3)"
    ordering="AFTER"
    side="BOTH"
